#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                     Carnegie Mellon University                        ##
##                         Copyright (c) 2013                            ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  Scoring file for vuv prediction                                      ##
##                                                                       ##
###########################################################################

cat $1 |
awk '{print $2}' |
while read x
do
   $ESTDIR/bin/ch_track -c 0 $2/$x.mcep |
   awk '{if ($1 < 1)
            print 0;
         else
            print 1;}' >p.$$.v

   $ESTDIR/bin/ch_track ccoefs/$x.mcep |
   awk '{if ($NF < 0.5)
            print 0;
         else
            print 1;}' >a.$$.v

   paste a.$$.v p.$$.v |
   awk '{if ($1 == $2)
         {
            c++
         }
         if (($1 == 0) && ($2 == 0))
         {
            c0++;
            c00++;
         }
         else if (($1 == 1) && ($2 == 0))
         {
            c1++;
            c10++;
         }
         else if (($1 == 0) && ($2 == 1))
         {
            c0++;
            c01++;
         }
         else if (($1 == 1) && ($2 == 1))
         {
            c1++;
            c11++;
         }
        }
        END {precision=(100.0*c11)/(c11+c01);
             recall=(100.0*c11)/c1;
             f1 = (200.0*c11)/((2*c11)+(c10)+c01);
             printf("c %5.2f p %5.2f r %5.2f f1 %5.2f c00 %5.2f c01 %5.2f c10 %5.2f c11 %5.2f c1 %d c0 %d n %d\n",(100.0*c)/NR,precision,recall,f1,(100.0*c00)/c0,(100.0*c01)/c0,(100.0*c10)/c1,(100.0*c11)/c1,c1,c0,NR)}'

   cp -pr a.$$.v a.v
   cp -pr p.$$.v p.v

   rm -f a.$$.* p.$$.v
done |
awk '{ c+=$2;
       p+=$4;
       r+=$6;
       f1+=$8;
       c00+=$10;
       c01+=$12;
       c10+=$14;
       c11+=$16;
       n+=$NF;
      }
      END {
       printf("%5.2f p %5.2f r %5.2f f1 %5.2f c00 %5.2f c01 %5.2f c10 %5.2f c11 %5.2f n %d\n",c/NR,p/NR,r/NR,f1/NR,c00/NR,c01/NR,c10/NR,c11/NR,n);}'
       

